[toolchain]
# Please also update the badges in `README.md`s (`error-stack` and `error-stack-macros`), and `src/lib.rs`
channel = "nightly-2023-10-30"
# Rust analyzer is not included in the original repo but it
# is manually added due to issues with the rust-analyzer LSP client.
components = ['rustfmt', 'clippy', 'llvm-tools-preview', 'miri', 'rust-src', 'rust-analyzer']
